require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SystemRequirementsController do

  # This should return the minimal set of attributes required to create a valid
  # SystemRequirement. As you add validations to SystemRequirement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SystemRequirementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all system_requirements as @system_requirements" do
      system_requirement = SystemRequirement.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:system_requirements)).to eq([system_requirement])
    end
  end

  describe "GET show" do
    it "assigns the requested system_requirement as @system_requirement" do
      system_requirement = SystemRequirement.create! valid_attributes
      get :show, {:id => system_requirement.to_param}, valid_session
      expect(assigns(:system_requirement)).to eq(system_requirement)
    end
  end

  describe "GET new" do
    it "assigns a new system_requirement as @system_requirement" do
      get :new, {}, valid_session
      expect(assigns(:system_requirement)).to be_a_new(SystemRequirement)
    end
  end

  describe "GET edit" do
    it "assigns the requested system_requirement as @system_requirement" do
      system_requirement = SystemRequirement.create! valid_attributes
      get :edit, {:id => system_requirement.to_param}, valid_session
      expect(assigns(:system_requirement)).to eq(system_requirement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SystemRequirement" do
        expect {
          post :create, {:system_requirement => valid_attributes}, valid_session
        }.to change(SystemRequirement, :count).by(1)
      end

      it "assigns a newly created system_requirement as @system_requirement" do
        post :create, {:system_requirement => valid_attributes}, valid_session
        expect(assigns(:system_requirement)).to be_a(SystemRequirement)
        expect(assigns(:system_requirement)).to be_persisted
      end

      it "redirects to the created system_requirement" do
        post :create, {:system_requirement => valid_attributes}, valid_session
        expect(response).to redirect_to(SystemRequirement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved system_requirement as @system_requirement" do
        # Trigger the behavior that occurs when invalid params are submitted
        SystemRequirement.any_instance.stub(:save).and_return(false)
        post :create, {:system_requirement => { "title" => "invalid value" }}, valid_session
        expect(assigns(:system_requirement)).to be_a_new(SystemRequirement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SystemRequirement.any_instance.stub(:save).and_return(false)
        post :create, {:system_requirement => { "title" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested system_requirement" do
        system_requirement = SystemRequirement.create! valid_attributes
        # Assuming there are no other system_requirements in the database, this
        # specifies that the SystemRequirement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(SystemRequirement).to receive(:update).with({ "title" => "MyString" })
        put :update, {:id => system_requirement.to_param, :system_requirement => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested system_requirement as @system_requirement" do
        system_requirement = SystemRequirement.create! valid_attributes
        put :update, {:id => system_requirement.to_param, :system_requirement => valid_attributes}, valid_session
        expect(assigns(:system_requirement)).to eq(system_requirement)
      end

      it "redirects to the system_requirement" do
        system_requirement = SystemRequirement.create! valid_attributes
        put :update, {:id => system_requirement.to_param, :system_requirement => valid_attributes}, valid_session
        expect(response).to redirect_to(system_requirement)
      end
    end

    describe "with invalid params" do
      it "assigns the system_requirement as @system_requirement" do
        system_requirement = SystemRequirement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SystemRequirement.any_instance.stub(:save).and_return(false)
        put :update, {:id => system_requirement.to_param, :system_requirement => { "title" => "invalid value" }}, valid_session
        expect(assigns(:system_requirement)).to eq(system_requirement)
      end

      it "re-renders the 'edit' template" do
        system_requirement = SystemRequirement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SystemRequirement.any_instance.stub(:save).and_return(false)
        put :update, {:id => system_requirement.to_param, :system_requirement => { "title" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested system_requirement" do
      system_requirement = SystemRequirement.create! valid_attributes
      expect {
        delete :destroy, {:id => system_requirement.to_param}, valid_session
      }.to change(SystemRequirement, :count).by(-1)
    end

    it "redirects to the system_requirements list" do
      system_requirement = SystemRequirement.create! valid_attributes
      delete :destroy, {:id => system_requirement.to_param}, valid_session
      expect(response).to redirect_to(system_requirements_url)
    end
  end

end
